version: '2'
services:
  app:
    build:
      context: ./app
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.6.38
    volumes:
      - "db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: cubecart
    ports:
      - "3306:3306"
volumes:
  db-volume:
